#!env node

const axios = require('axios')
const app = require('../src/index')
const chai = require('chai')
const chaiHttp = require('chai-http')
const config = {
  port: 3000
};

//CLEAR DATABASE
const client = require('../src/dbClient')
client.flushall();

//PUSH EMPLOYEE
(async function() {
try{
  await Promise.all([{
	datetime: 1617616800000,
	nom: 'station 1',
	pollution: '2000',
},{
	datetime: 1617530400000,
	nom: 'station 1',
	pollution: '500',
},{
	datetime: 1617307200000,
	nom: 'station 1',
	pollution: '500',
},{
	datetime: 1617566400000,
	nom: 'station 1',
	pollution: '1000',
},{
	datetime: 1617703200000,
	nom: 'station 1',
	pollution: '700',
},{
	datetime: 1617393600000,
	nom: 'station 1',
	pollution: '500',
},{
	datetime: 1617480000000,
	nom: 'station 1',
	pollution: '800',
},,{
	datetime: 1617789600000,
	nom: 'station 1',
	pollution: '500',
}].map( async (mesure) => {
	 console.log(mesure.pollution)
	 await axios.post(`http://localhost:${config.port}/mesure`, (mesure))
  }))
  
  if(!process.env.INIT_BACKEND)
  {
  	console.log("Data pushed, server closed")
  	process.exit()
  }
  console.log("Initialization done")
}catch(err){
console.log(err)
process.exit()
}
})();

